### ISSUE TITLE
How to verify SMS API webhook events

### ISSUE THREAD

**Issue by Krupskis** [sinch/voice-api-webhook-nodejs#1]
Thanks Roland for your work. Is there a sinch code example to verify SMS API Incoming Message events? Those events don't have Authorization header it seems.

**Comment by 0xROLANDIAN** [comment]
Hi, I'm only working with Voice. But as I understand it the SMS API sends a token which can be verified as the same token you have in the dashboard. https://developers.sinch.com/docs/sms/tutorials/node/delivery-feedback/next_3.
 I will reach out to somebody in that team and clarify for you here.

**Comment by Krupskis** [comment]
Much appreciated, as the documentation is lacking on this issue 🙏

**Comment by Krupskis** [comment]
For reference these are the headers with SMS API incoming message webhook:
```
{'Host': '0538-90-131-32-168.ngrok.io', 'User-Agent': 'Apache-HttpClient/4.5.14 (Java/11.0.19)', 'Content-Length': '217', 'Accept-Encoding': 'gzip,deflate', 'Content-Type': 'application/json', 'X-Forwarded-For': '54.173.29.238', 'X-Forwarded-Proto': 'https'}
```

**Comment by roland-sinch** [comment]
I have checked internally and am waiting for some clarification on adding an authentication header.

**Comment by roland-sinch** [comment]
You will have to open a ticket with Sinch support to get the headers added for SMS, a authentication header is not added by default. Please reach out here.  https://tickets.sinch.com/plugins/servlet/desk/portal/31
